### PR TITLE
Fix/if s<0.5, get_retrievability return NaN

### PR DESCRIPTION
**Pull request by ishiko732**

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
The retrievability of new card should be undefined because we don't know it's stability.

image

**Comment by ishiko732** [comment]
> The retrievability of new card should be undefined because we don't know it's stability.

In the long-term scheduler, if the first click is 'Again' and it is counted as a 'Review' card, and if `s_0 < 0.5`, the `get_retrievability` method returns `NaN`. Should it return `undefined` instead?

**Comment by ishiko732** [comment]
https://github.com/open-spaced-repetition/ts-fsrs/blob/49b9566733cfe7cf5f9e82b93aec99985b21caa1/src/fsrs/fsrs.ts#L216

Or should I use `Math.ceil`?

> Math.round(0.4072) -> 0
> Math.ceil(0.4072) -> 1

**Comment by L-M-Sherlock** [comment]
I recommend `const r = this.forgetting_curve(t, processedCard.stability.toFixed(2))`.

**Comment by ishiko732** [comment]
> I recommend `const r = this.forgetting_curve(t, processedCard.stability.toFixed(2))`.

I have made the changes; now using toFixed(2).

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Pull request merged**
