### PR TITLE
Feat/Impl `initSeed`& `Scheduler` extension based on the strategy pattern

### PR DESCRIPTION
**Pull request by ishiko732**
I attempted to implement these #131 features using the proxy pattern but found it difficult for developers to integrate, so I opted for a similar design pattern instead. Does anyone have other suggestions or better ideas?

---

Proxy pattern:
9c106da5fc5ba792bb776386f4b9409

Strategy pattern:
image

### CODE REVIEW

**Comment by joshdavham** [comment]
@ishiko732 Hey man. I really wish I could help here, but I'm not familiar with either the Proxy or Stategy patterns so I don't really have an opinion on which would be preferrable here.

**Comment by asukaminato0721** [comment]
js has [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to be used with `Reflect`.
Or, what is the ideal API design?

**Comment by ishiko732** [comment]
> js has [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to be used with `Reflect`. Or, what is the ideal API design?

The ideal API design is such that developers don’t have to write excessive logic to implement functionality. Using [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) requires developers to understand trap methods like get and apply, and if the proxy passed in by developers is not suitable, it could lead to errors like `xxx is not a function`

**Comment by asukaminato0721** [comment]
emm, assume the library is finished, how will the api look like?

**Comment by ishiko732** [comment]
> emm, assume the library is finished, how will the api look like?

I hope the invocation would be like this:

Proxy pattern
```typescript
import {createEmptyCard, fsrs, Rating, Grades, Card} from 'ts-fsrs';

function ProxyHandler(this: AbstractScheduler) {
  return {
    apply: function (this: AbstractScheduler) {
      const card_id = Reflect.get(this, 'card_id') ?? 0
      const reps = Reflect.get(this, 'reps') ?? 0
      return String(card_id + reps || 0)
    }.bind(this),
  }
}
const f = fsrs().useProxy(ProxyMode.SEED, ProxyHandler);
// or const f= fsrs(params, proxies)

const now = new Date()
const card = createEmptyCard(now, (card: Card) => {
  Object.assign(card, { card_id: 1234 })
  return card
})
f.repeat(card, now);
```

Strategy pattern
```typescript
import {createEmptyCard, fsrs, Rating, Grades, Card} from 'ts-fsrs';


function StrategyHandler(this: AbstractScheduler): string {
   const card_id = Reflect.get(this.current, card_id_field) ?? 0
   const reps = this.current.reps
   return String(card_id + reps || 0)
}
const f = fsrs().useStrategy(StrategyMode.SEED, StrategyHandler);
// or const f= fsrs(params, strategies)

const now = new Date()
const card = createEmptyCard(now, (card: Card) => {
  Object.assign(card, { card_id: 1234 })
  return card
})
f.repeat(card, now);
```

**Review by asukaminato0721 — APPROVED** [review]

**Pull request merged**
